spring:
  #配置数据库链接等数据源
  #使用druid做链接池管理
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/dianpingdb?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
  redis:
    host: 127.0.0.1
    port: 6379
  #add-mappings=true表示如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配
  resources:
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
    #接入前端静态资源页面
    static-path-pattern: /static/**
  #thymeleaf相关的配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 120
#admin官方账号的用户名和密码
admin:
  email: admin@imooc.com
  encryptPassword: 4QrcOUm6Wau+VuBX8g+IPg==